name: flutter_pdfview_platform_interface
description: A common platform interface for the flutter_pdfview plugin.
homepage: https://github.com/endigo/flutter_pdfview
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.0.0

dev_dependencies:
#  flutter_test:
#    sdk: flutter
