name: flutter_pdfview_web
description: A Flutter plugin that provides a PDFView widget on Web.
version: 2.0.0
homepage: https://github.com/endigo/flutter_pdfview

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_pdfview_platform_interface:
    path: ../flutter_pdfview_platform_interface/
  js: ^0.6.3

dev_dependencies:
#  flutter_test:
#    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: PDFViewFlutterPlugin
        fileName: flutter_pdfview_plugin.dart

  assets:
    - packages/flutter_pdfview_web/assets/require.js
    - packages/flutter_pdfview_web/assets/flutter_pdfview.js
