name: flutter_pdfview
description: A Flutter plugin that provides a PDFView widget on Android and iOS.
version: 2.0.0
homepage: https://github.com/endigo/flutter_pdfview

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter

  flutter_pdfview_platform_interface:
    path: ../flutter_pdfview_platform_interface/
  flutter_pdfview_web:
    path: ../flutter_pdfview_web/

dev_dependencies:
#  flutter_test:
#    sdk: flutter

  pedantic: ^1.11.0
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.endigo.plugins.pdfviewflutter
        pluginClass: PDFViewFlutterPlugin
      ios:
        pluginClass: FLTPDFViewFlutterPlugin
      web:
        default_package: flutter_pdfview_web
